// 네트워크 핵심 용어 사전
const glossary = {
  "Host": "PC, 스마트폰, 서버 등 네트워크 앱이 실행되는 끝 장치. End system이라고도 부른다.",
  "End System": "Host와 같은 말. 네트워크 가장자리에서 앱을 실행하는 장치.",
  "Router": "패킷의 목적지 주소를 보고 다음 경로로 전달(forwarding)하는 네트워크 코어 장비.",
  "Switch": "같은 네트워크(LAN) 안에서 MAC 주소 기반으로 프레임을 전달하는 장비.",
  "Packet": "전송할 데이터를 일정 크기로 쪼갠 단위. header + payload로 구성된다.",
  "Protocol": "통신 규칙. 메시지의 형식(format), 순서(order), 동작(action)을 정의한다.",
  "ISP": "Internet Service Provider. 인터넷 접속 서비스를 제공하는 사업자.",
  "Bandwidth": "링크가 초당 전송할 수 있는 최대 bit 수. 단위는 bps.",
  "Throughput": "실제로 end-to-end 전달되는 속도. 가장 느린 링크(병목)에 의해 결정된다.",
  "Latency": "패킷이 출발지에서 목적지까지 도달하는 데 걸리는 시간.",
  "RTT": "Round Trip Time. 패킷이 갔다가 돌아오는 데 걸리는 시간.",
  "Store-and-forward": "라우터가 패킷 전체를 수신한 뒤에야 다음 링크로 전송을 시작하는 방식.",
  "Queueing delay": "라우터의 출력 큐에서 앞선 패킷들이 처리될 때까지 대기하는 시간.",
  "Packet loss": "라우터의 큐(버퍼)가 꽉 차서 도착한 패킷을 버리는 현상.",
  "FDM": "Frequency Division Multiplexing. 주파수 대역을 나눠서 각 사용자에게 할당.",
  "TDM": "Time Division Multiplexing. 시간을 슬롯으로 나눠서 각 사용자에게 할당.",
  "TCP": "Transmission Control Protocol. 신뢰적, 순서 보장, 혼잡 제어를 제공하는 전송 계층 프로토콜.",
  "UDP": "User Datagram Protocol. 최소 기능만 제공하는 빠르고 단순한 전송 계층 프로토콜.",
  "IP": "Internet Protocol. 네트워크 계층에서 패킷의 주소 지정과 라우팅을 담당.",
  "DNS": "Domain Name System. 도메인 이름(예: google.com)을 IP 주소로 변환하는 분산 DB.",
  "HTTP": "HyperText Transfer Protocol. 웹에서 클라이언트-서버 간 통신을 위한 응용 계층 프로토콜.",
  "SMTP": "Simple Mail Transfer Protocol. 이메일을 전송(push)하는 프로토콜.",
  "Encapsulation": "상위 계층 데이터에 하위 계층 header를 붙이는 과정. 수신 측에서 역순으로 벗긴다.",
  "Malware": "악성 소프트웨어. 호스트에 침투해 데이터를 탈취하거나 봇넷을 구성한다.",
  "DDoS": "Distributed Denial of Service. 다수의 좀비 호스트가 동시에 트래픽을 보내 서버를 마비시키는 공격.",
  "Spoofing": "패킷의 출발지 주소를 위조하여 보내는 공격 기법.",
  "Sniffing": "네트워크상의 패킷을 몰래 가로채서 내용을 엿보는 행위.",
  "NAT": "Network Address Translation. 사설 IP를 공인 IP로 변환하여 여러 장치가 하나의 공인 IP를 공유.",
  "DHCP": "Dynamic Host Configuration Protocol. IP 주소를 자동으로 할당해주는 프로토콜.",
  "ARP": "Address Resolution Protocol. IP 주소로부터 MAC 주소를 알아내는 프로토콜.",
  "MAC": "Media Access Control. 링크 계층에서 장치를 식별하는 물리 주소 (48-bit).",
  "Socket": "프로세스가 네트워크로 데이터를 보내고 받는 인터페이스. 앱과 전송 계층 사이의 문.",
  "Port": "하나의 호스트 안에서 여러 프로세스를 구분하기 위한 번호 (0~65535).",
  "Congestion control": "네트워크 혼잡을 감지하고 전송 속도를 조절하는 TCP의 메커니즘.",
  "Flow control": "수신자의 버퍼가 넘치지 않도록 송신 속도를 조절하는 메커니즘.",
  "CDN": "Content Delivery Network. 콘텐츠 복사본을 여러 지역 서버에 배치하여 가까운 곳에서 제공.",
  "DASH": "Dynamic Adaptive Streaming over HTTP. 네트워크 상태에 따라 비디오 품질을 자동 조절.",
  "P2P": "Peer-to-Peer. 서버 없이 참여자들이 서로 데이터를 주고받는 구조.",
  "BGP": "Border Gateway Protocol. 자율 시스템(AS) 간 라우팅 정보를 교환하는 프로토콜.",
  "OSPF": "Open Shortest Path First. AS 내부에서 최단 경로를 계산하는 라우팅 프로토콜.",
};

export default glossary;
